### ISSUE TITLE
Feature: Logging

### ISSUE THREAD

**Issue by chrisw000** [dougdellolio/gdax-csharp#105]
Now the codebase has pretty decent funnels which core functionality flows down... it's ripe to add in some logging.

The user story for this use case would be along the lines of "As an automated Trader risking £bundles, when I use XYZ API, if (when) it goes wrong..... I want to know why, so I can understand and fix the error."

There is a crystal clear requirement for robust logging on any API such as this.... the only questions are:
* Which logging system to use
* How deeply logging is available vs how much maintenance is required to keep logging in step with functionality

I would argue that NLog is the defacto .NET logger these days.... so the first question is a moot point.

The second question is loaded, obviously less is more until proven otherwise.

So.... it would be good to have NLog as part of the codebase, and I'd suggest initially only logging placed only at strategic dataflow or logic points:

INFO - `GDAXClient` - construction for activity datetime

DEBUG - `AbstractService.SendServiceCall `- log the `IEndPoint` data of httpMethod/uri/content

TRACE - `AbstractService.SendHttpRequestMessageAsync` - log the httpResponseMessage

INFO - `WebSocket` - startup / parameters

INFO - `WebSocket` - close

DEBUG - `WebSocket` - minimal info on data recieved

TRACE - `WebSocket` - raw channel json data coming in

ERROR - Any Exception captures

ERROR - Add Try Catch around the central JSON serialize / deserialize + log

ERROR - Provide some ability to switch on `MissingMemberHandling = MissingMemberHandling.Error` on the JSON serialize/deserialize settings - thus automatically logging / being told about missing Model properties for new json output ---> primarily for development use only

--> Ship with a sample NLog config that allows someone who has never used NLog before to direct logging to \bin\gdax-sharp.log or console, or [Sentinel](https://github.com/yarseyah/sentinel) etc.

Happy to do the work....

**Comment by dougdellolio** [comment]
this would be great! NLog is 👍

**Comment by jonnii** [comment]
> NLog is the defacto .NET logger

it is not, and an open source project shipping with a specific logger is problematic for many reasons:

1. Not everyone uses nlog (what if I use serology)
2. What if I don't use _the version of nlog you use_ (i might be on 2.x).
3. Your log levels are not my log levels

you're better off solving this by either having an interface like:

```
public interface IInstrumentationSink {
  void OnWebSocketCreated(WebSocket ws);
  void OnWebSocketClosed(WebSocket ws);
  void OnException(Exception e);
  void OnServiceCall(...);
}
```

By default this is a `NullInstrumentationSink` but consumers can implement this and decide on the log messages (and log levels) that they are interested in themselves. 

Alternatively (and a better option imo) is to try to use a middleware pattern but that is likely a bigger and more disruptive change.

**Comment by chrisw000** [comment]
@jonnii 
I hear what you're saying.... and don't agree.

on your points
1) Today there is no logging. This proposal is a Minimum Viable Product style improvement, not a final solution.
2) Use assembly redirection, or upgrade. We don't all still use COBOL and the world moves on
3) It open source. Change it then and allow flexibility via your change

I do agree that an interface would offer total flexibility - but it's also telling the users to write their own implementation - and this is logging, which is not complicated. If you want total control - fork the repo

Nothing is perfect or finished, especially not on its first iteration of any improvement - so no doubt there will be a series of future pull requests to change and improve whatever the first version of logging is.

I look forward to your pull request improving whatever I may contribute.

**Comment by jonnii** [comment]
All of your points are absolutely correct, the only thing I take issue with is the assertion that "nlog is the defacto standard" which it's not. I also think it's important to have these conversations and have people contribute to the discussion ahead of an implementation, which I assume you also do as you opened an issue instead of going straight to opening a PR.

**Comment by dougdellolio** [comment]
@chrisw000  i think logging in this library would be great and offer a lot to the users. however, i don't think we should make such a change that would be majorly disruptive.

would you guys be against offering the flexibility to the user to define their logs how they want but also offer a default implementation - whatever that may be (maybe what you proposed above).  I also do happen to like Serilog

thoughts on that?

**Comment by BradForsythe** [comment]
Logging is totally needed for those of us who are running hundreds (maybe tens!)  of algo's and need to troubleshoot or optimize order chains.    

One very important area to instrument with whatever logging you implement is the websocket connection and feeds.   I implemented my own websocket interface because my connections are long running(continuous) and GDAX sometimes stalls, connection sometimes closes, feeds can be irregular and I do keep a mini order book updated realtime using l2updates and need to know feed status (not just socket status) at all times.   So long story shortened...instrument websocket connections, feeds, subscriptions, etc.  That would be awesome.   Also if you really are energetic  time stamping orders, potentially order entry statistics such as request/response timing.

If the logging is going to be runtime enabled (not just compiled out in release mode), make sure it doesn't place an overhead on order entry (consider doing any writing to log files after order is placed if possible).   I haven't found any log to cache and flush to file, but I have written a fairly crappy one.   That solves the issue of logging for time critical functions.

Anyway, just a few things to think about...great idea here...

**Comment by chrisw000** [comment]
@dougdellolio  - been away... back now....

If we're wanting total flexibility ( with a default implementation and/or sample configs etc. ) - then really this is ultimately what @jonnii  was saying.

In which case.... it does need some direction in terms of the preferred implementation route.

**Comment by dougdellolio** [comment]
@chrisw000 fair enough. I think i would prefer serilog

**Comment by chrisw000** [comment]
ok... I've looked at Serilog now...

As I use NLog everywhere I've been motivated to also look for a proxy logging solution.... ( that doesn't require users to implement their own provider to a sink interface)

Long story short - the 3 popular proxy logging solutions I looked at each have issues which make them nonviable at least today... 

So I'll concede defeat and just do something for Serilog.   :)
