### ISSUE TITLE
status:WaitingForActivation

### ISSUE THREAD

**Issue by anna1981-t** [dougdellolio/gdax-csharp#38]
Hi, I get a status message saying WaitingForActivation. Is there something I am doing incorrectly? Can you help?
thanks

anna

**Comment by dougdellolio** [comment]
Hi,

Are you trying to use the GDAX sandbox? If yes, it is currrently down (and has been for the last week or so unfortunately) which may explain the “waiting” status. 

If not, can you provide some code?

**Comment by cquinterox** [comment]
I ran into this message as well. I ran into this because I paused the debugger on an **async** call. 

For example the following line gave me the message you stated when paused:
`var cancelOrderById = gdaxClient.OrdersService.CancelOrderByIdAsync(cancelId);`

Adding **Result** to the end will cause the code to be executed synchronously and _should_ give you answer you are expecting. 

`var cancelOrderById = gdaxClient.OrdersService.CancelOrderByIdAsync(cancelId).Result;`

However I do recommend you read some better material on await and async if that was the cause of your problem.
