### ISSUE TITLE
Issue with GTT(Good Till Canceled)

### ISSUE THREAD

**Issue by mamohanc** [dougdellolio/gdax-csharp#54]
I encountered the following :
1) The GTT order is not canceled, even though I have specified the parameter as GTT, and timeinforce "min"
2) Unlike the UI, limit buy orders are not canceled(rejected) when placed "at a greater than current price"  through the API. rather they turn into "fees charging" orders, and get fullfilled.
3) Also when a limit order is placed, the status of the order(based on the GUID sent), is showing as pending inspite of the order being filled.  
4) it is taking 1-2 sec atleast for the response to come back.

The issue(doubts) above may not be due to the API client,  but am I missing anything ?
BTW thanks for the API Client

**Comment by dougdellolio** [comment]
@mamohanc my responses below

> 1. The GTT order is not canceled, even though I have specified the parameter as GTT, and timeinforce "min"

For limit orders that are GTT, all you need to do is specify the DateTime you want the order to be cancelled (https://github.com/dougdellolio/gdax-csharp/blob/master/GDAXClient/Services/Orders/OrdersService.cs#L87). If you are referring to setting the cancel date to `DateTime.MinValue`, the date of 1/1/0001 12:00:00AM will be returned so the order will never be cancelled. I would suggest using the "Fill or Kill" order by setting the `TimeInForce` to `FoK` if you want an order to be either filled immediately or cancelled.

> 2. Unlike the UI, limit buy orders are not canceled(rejected) when placed "at a greater than current price" through the API. rather they turn into "fees charging" orders, and get fullfilled.

Never noticed this.... this is an interesting one. Is this a problem not on the sandbox as well? I need to dig a bit further.

> 3. Also when a limit order is placed, the status of the order(based on the GUID sent), is showing as pending inspite of the order being filled.

This is due to the order being filled after the response comes back from the API. One way around this is by using the Order Id in the response and using the `GetOrderByIdAsync` call to look at the `done_reason`.

> 4. it is taking 1-2 sec atleast for the response to come back.

I notice this as well and don't believe its due to anything in the client. GDAX offers a FIX api to enter orders, submit/cancel requests, and receive fills which would give overall faster execution speeds. This is not implemented here yet.

Thanks for opening these issues here and I will see if I can dig deeper into number 2 😃

**Comment by mamohanc** [comment]
That was pretty quick response
1) **The GTT order is not canceled, even though I have specified the parameter as GTT, and timeinforce "min"**

For limit orders that are GTT, all you need to do is specify the DateTime you want the order to be cancelled (https://github.com/dougdellolio/gdax-csharp/blob/master/GDAXClient/Services/Orders/OrdersService.cs#L87). If you are referring to setting the cancel date to DateTime.MinValue, the date of 1/1/0001 12:00:00AM will be returned so the order will never be cancelled. I would suggest using the "Fill or Kill" order by setting the TimeInForce to FoK if you want an order to be either filled immediately or cancelled.
**I would have misunderstood it as i have overriden your DateTime.Now (I am confused why it was having _cancelAfter.Minute + "," + cancelAfter.Hour + "," + cancelAfter.Day_.  and i have sent "min" instead into that parameter, as from the docs.gdax i understood it that way. 
So what would be the exact text into that field if i were to place an order at 
2018-01-27 11:43:22.222 (just a timestamp to be specific)**

2) **Unlike the UI, limit buy orders are not canceled(rejected) when placed "at a greater than current price" through the API. rather they turn into "fees charging" orders, and get fullfilled.**
Never noticed this.... this is an interesting one. Is this a problem not on the sandbox as well? I need to dig a bit further.
**(SandBox ?, I understood from various texts that sandbox has been deprecated. )**


3) **Also when a limit order is placed, the status of the order(based on the GUID sent), is showing as pending inspite of the order being filled.**
This is due to the order being filled after the response comes back from the API. One way around this is by using the Order Id in the response and using the GetOrderByIdAsync call to look at the done_reason.

**Yeah, thats what i tried. I have verified it over a course of 3-4 requests being sent to GetOrderByIdAsync
and it still gives me "pending" even after the order is fullfilled (i.e pending status even after 20 secs of fullfillment).** 


**4) it is taking 1-2 sec atleast for the response to come back.**
I notice this as well and don't believe its due to anything in the client. GDAX offers a FIX api to enter orders, submit/cancel requests, and receive fills which would give overall faster execution speeds. This is not implemented here yet.

hmmm yeah FIX API, have read on the gdax but never looked into it. Any good repositories already implementing that, that you know of? Do you really think it would be faster like in the range of 0.5 sec ?

Have a great weekend, coding stuff :)

**Comment by dougdellolio** [comment]
@mamohanc some responses for you

1. Ahh this is a bug, nice catch :) The original interpretation was passing in an actual date when really you are given three choices - minute, hour, day. I have added a fix to this PR here: https://github.com/dougdellolio/gdax-csharp/pull/57 please try it out and let me know if you agree with it/if it works for you. Instead of a date you pass in an enum of min, hour, day.

2. I was trying limit orders out in the Sandbox and saw this behavior so wasn't sure if it was on the live servers too. Haven't found anything else on this yet unfortunately but if you find any issue with the client feel free to open a PR with a fix.

3. Hm that is really weird. I am not sure I can answer as to why. You may have to provide code since it might be related to how it is being used?? On my end I am able to see the `Done_reason` as `filled` under GetOrderByIdAsync immediately after the order is filled. 

4. I am unaware of any libraries that exist in C#. If there are enough requests I could take a shot at implementing it :) I am sure it would be faster as they are used by banks and hedge funds that depend on quick execution times.

**Comment by nadasurf2** [comment]
Just chiming in on #2, I'm seeing the same behavior on the live servers too. I'm not talented enough to offer up a suggested fix however
But on another note, thanks for your work on this. it's been great

**Comment by dougdellolio** [comment]
@nadasurf2 thanks! 

there is a fix in PR #57. Will merge and release shortly

**Comment by dougdellolio** [comment]
all fixed with v1.10 - please update. feel free to open another issue if you find anything wrong. closing this for now

**Comment by nadasurf2** [comment]
Thanks Doug, although not necessarily a bug, now when calling PlaceLimitOrderAsync in v1.10 with PowerShell you get error

Multiple ambiguous overloads found for "PlaceLimitOrderAsync" and the argument count: "6"

I’ve done some searching and I’m not really sure there’s a way around it

**Comment by dougdellolio** [comment]
sounds like it's not sure which method to choose? maybe try explicitly setting the default parameters.

so if you were using this one: https://github.com/dougdellolio/gdax-csharp/blob/master/GDAXClient/Services/Orders/OrdersService.cs#L54

you can do something like

`.PlaceLimitOrderAsync(OrderSide.Buy, ProductType.BtcUsd, 1, 12000, TimeInForce.Gtc, true)`
