### ISSUE TITLE
StatusCode: 400, ReasonPhrase: 'Bad Request'

### ISSUE THREAD

**Issue by RaceX58** [dougdellolio/gdax-csharp#62]
Hello,

I'm trying to use this library in a WPF C# Project.

this function :
`  var gdaxClient = new GDAXClient.GDAXClient(authenticator, false);
            var orders = await gdaxClient.OrdersService.GetAllOrdersAsync(10);`

Returns me :
> StatusCode: 400, ReasonPhrase: 'Bad Request'

at this line :
`var httpResponseMessage = await httpClient.SendASync(httpRequestMessage).ConfigureAwait(false);`

I have no problem using this function:
`var products = await gdaxClient.ProductsService.GetAllProductsAsync();`

Is there something I'm doing wrong?

Thanks in advance.

**Comment by dougdellolio** [comment]
@RaceX58 
hm... its hard to say exactly where this is going wrong. i was able to try the `GetAllOrdersAsync(10)` without failure. please make sure you have the latest version v1.0.11.

Let me know if you can find where the issue is. If you would like to contribute feel free to open up a pull request.

If none of the above work then I would suggest posting some more code to see if I can help spot any issues (omit all credentials).

thanks!
