### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by lycxy09** [dougdellolio/gdax-csharp#99]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1003	Syntax error, ',' expected	GDAXSharp	D:\gdax-csharp\GDAXSharp\Services\AbstractService.cs	76	Active
Error	CS1003	Syntax error, ',' expected	GDAXSharp	D:\gdax-csharp\GDAXSharp\Services\AbstractService.cs	103	Active
Error	CS0103	The name 'var' does not exist in the current context	GDAXSharp	D:\gdax-csharp\GDAXSharp\Services\AbstractService.cs	76	Active
Error	CS0103	The name 'firstPageAfterCursorId' does not exist in the current context	GDAXSharp	D:\gdax-csharp\GDAXSharp\Services\AbstractService.cs	76	Active
Error	CS0103	The name 'firstPageAfterCursorId' does not exist in the current context	GDAXSharp	D:\gdax-csharp\GDAXSharp\Services\AbstractService.cs	81	Active
Error	CS0103	The name 'var' does not exist in the current context	GDAXSharp	D:\gdax-csharp\GDAXSharp\Services\AbstractService.cs	103	Active
Error	CS0103	The name 'cursorHeaders' does not exist in the current context	GDAXSharp	D:\gdax-csharp\GDAXSharp\Services\AbstractService.cs	103	Active
Error	CS0103	The name 'cursorHeaders' does not exist in the current context	GDAXSharp	D:\gdax-csharp\GDAXSharp\Services\AbstractService.cs	108	Active

**Comment by dougdellolio** [comment]
hm.. i would try a fresh clone if you are seeing these errors. do you receive this error on build?

**Comment by lycxy09** [comment]
Yes, I use a refresh clone and got this error when I build it.

2018-03-23 18:03 GMT-05:00 Doug Dellolio <notifications@github.com>:

**Comment by dougdellolio** [comment]
sounds like possibly not recognizing C#7 syntax? what IDE are you using and what version?

**Comment by chrisw000** [comment]
Just as a side note on this.... obviously the code builds because it compiles on Travis.... but... I did open the project in VS2015 by mistake the other day... and I got these "errors"

It's clearly a C# 7 thing..... and the answer is always on [StackOverflow](https://stackoverflow.com/questions/39461407/how-to-use-c7-with-visual-studio-2015)

I guess it wouldn't hurt to be specific about VS2017 at the top of the read me... and anyone who doesn't know how to work this out should really be using the NuGet packages anyway?
